Fixed attempt of buckets update before map first render
Time to time, randomly Datadog RUM that is monitoring our application FE reports the following error

```
TypeError: undefined is not an object (evaluating 'i.style.listImages')
  at updateBuckets @ https://example.com/_next/static/chunks/153e222f-eb05776e76b311d1.js:8:55922
  at refreshFeatureState @ https://example.com/_next/static/chunks/153e222f-eb05776e76b311d1.js:8:55812
  at initializeTileState @ https://example.com/_next/static/chunks/153e222f-eb05776e76b311d1.js:8:68593
  at _tileLoaded @ https://example.com/_next/static/chunks/153e222f-eb05776e76b311d1.js:8:73285
  at u @ https://example.com/_next/static/chunks/153e222f-eb05776e76b311d1.js:8:27141
  at processTask @ https://example.com/_next/static/chunks/153e222f-eb05776e76b311d1.js:7:292692
  at receive @ https://example.com/_next/static/chunks/153e222f-eb05776e76b311d1.js:7:292534
```

As `Painter` `style` property is being initialised in the `render` method instead of `constructor`, it seems that `updateBuckets` might be occasionally called even before the first map render when painter is not ready to do their job.